version: '4.0'
services:
  mysqlsvc:
    container_name: mysql-service
    image: mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sba
      MYSQL_USER: root
    volumes:
      - $PWD/data/mysql/shell/:/docker-entrypoint-initdb.d/
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 6606:3306
  eureka:
    container_name: eureka-service
    image: eureka-service:sba
    build:
      context: ./eureka
    restart: always
    expose:
      - 8761
    ports:
      - 8761:8761
  zuulGatewayService:
    container_name: zuul-service
    image: zuul-service:newsapp
    depends_on:
      - netflixeurekanamingserver
      - zipkinsvc
      - rabbitmqsvc
    build:
      context: ./zuul-gateway-server
    restart: always
    expose:
      - 8765
    ports:
      - 8765:8765
    external_links:
      - netflixeurekanamingserver
      - rabbitmqsvc
      - zipkinsvc
    environment:
      - EUREKA_URL=http://netflixeurekanamingserver:8761/eureka/
      - ZIPKIN_URL=http://zipkinsvc:9411
      - RABBITMQ_HOST=rabbitmqsvc
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  recommendationService:
    container_name: recommendation-service
    image: recommendation-service:newsapp
    depends_on:
      - netflixeurekanamingserver
      - zipkinsvc
      - rabbitmqsvc
      - mongoservice
    build:
      context: ./articleRecommendationService
    restart: always
    expose:
      - 9300
    ports:
      - 9300:9300
    external_links:
      - eureka
    environment:
      - EUREKA_URL=http://eureka:8761/eureka/
  favouriteService:
    container_name: favourite-service
    image: favourite-service:newsapp
    depends_on:
      - netflixeurekanamingserver
    build:
      context: ./favouriteservice
    restart: always
    expose:
      - 9200
    ports:
      - 9200:9200
    external_links:
      - netflixeurekanamingserver
    environment:
      - EUREKA_URL=http://netflixeurekanamingserver:8761/eureka/
  userService:
    container_name: user-service
    image: user-service:newsapp
    depends_on:
      - netflixeurekanamingserver
      - zipkinsvc
      - rabbitmqsvc
      - mysqlsvc
    build:
      context: ./userservice
    restart: always
    expose:
      - 9100
    ports:
      - 9100:9100
    external_links:
      - netflixeurekanamingserver
      - rabbitmqsvc
      - zipkinsvc
      - mysqlsvc
    environment:
      - EUREKA_URL=http://netflixeurekanamingserver:8761/eureka/
      - MYSQL_HOST=mysqlsvc
  frontendService:
    container_name: frontend-service
    image: fzmfu/newsapp-frontend:v1
    restart: always
    external_links:
      - zuulGatewayService
    expose:
      - 80
    ports:
      - 4100:80