spring:
  application:
    name: sba-eureka
server:
  port: 8761

# Service management configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"        #Exposed interfaces, "*" indicates all web monitoring interfaces
        exclude:            #Leak proof interface
      base-path: /actuator  #Monitoring root path
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.netflix.eureka: 'OFF'
    com.netflix.discovery: 'OFF'
