spring:
  application:
    name: sba-gateway
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #${EUREKA_URL}
  instance:
    securePortEnabled: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
      base-path: /actuator
  endpoint:
    health:
      show-details: ALWAYS
apiurl:
  gatewayurl: http://localhost:8765
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    sba-payment:
      path: /payment/**
      serviceId: sba-payment
    sba-search:
      path: /search/**
      serviceId: sba-search
    sba-security:
      path: /security/**
      serviceId: sba-security
      stripPrefix: true
      sensitiveHeaders: Cookie,Set-Cookie # Exclude authorization from sensitive headers 
    sba-technology:
      path: /technology/**
      serviceId: sba-technology
    sba-training:
      path: /training/**
      serviceId: sba-training
    sba-user:
      path: /user/**
      serviceId: sba-user
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 30000
swagger.enabled: true